🗃️ Changes on entities
 Removing length property in Poi entity file.
 "It crashes server as this error message appears :
 TypeORMError: Column customize_gps_marker of Entity Poi does not support length property."

  To be fixed on poi_crud branch